import esbuild from "esbuild";
import process from "process";
import { builtinModules, createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import path from 'node:path';

const _require = createRequire(import.meta.url);

/** Strip // line comments from JSONC and bundle as JSON.
 *  Also bypasses package.json `exports` restrictions for .jsonc files. */
const jsoncPlugin = {
	name: 'jsonc',
	setup(build) {
		// Bypass exports field for textlint-rule-terminology/terms.jsonc
		build.onResolve({ filter: /textlint-rule-terminology\/terms\.jsonc$/ }, () => {
			const pkgDir = path.dirname(_require.resolve('textlint-rule-terminology'));
			return { path: path.resolve(pkgDir, '..', 'terms.jsonc') };
		});

		build.onLoad({ filter: /\.jsonc$/ }, (args) => {
			const text = readFileSync(args.path, 'utf8');
			// Remove single-line comments
			const stripped = text.replace(/\/\/[^\n]*/g, '');
			return { contents: stripped, loader: 'json' };
		});
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [jsoncPlugin],
	entryPoints: ["src/main.ts"],
	bundle: true,
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
